export const POST_CATEGORIES = [
  "Math",
  "ADDMA",
  "Additional Math",
  "Physics",
  "Chemistry",
  "Biology",
  "Computer Science",
  "Engineering",
  "Statistics",
  "Data Science",
  "Engineering Mathematics",
  "Applied Mathematics",
  "Pure Mathematics",
  "Artificial Intelligence",
  "Machine Learning",
  "Environmental Science",
  "Earth Science",
  "Astronomy",
  "Geology",
  "Medicine",
  "Nursing",
  "Dentistry",
  "Pharmacy",
  "Public Health",
  "Anatomy",
  "Physiology",
  "Pathology",
  "Microbiology",
  "Neuroscience",
  "Nutrition",
  "Kinesiology",
  "Business",
  "Finance",
  "Accounting",
  "Economics",
  "Marketing",
  "Management",
  "Entrepreneurship",
  "Human Resources",
  "Operations",
  "Supply Chain",
  "Real Estate",
  "Insurance",
  "History",
  "Geography",
  "Philosophy",
  "Literature",
  "Linguistics",
  "Political Science",
  "Sociology",
  "Psychology",
  "Anthropology",
  "Archaeology",
  "Religious Studies",
  "Cultural Studies",
  "International Relations",
  "Law",
  "Criminal Justice",
  "Public Policy",
  "Government",
  "Constitutional Studies",
  "Legal Studies",
  "Education",
  "Architecture",
  "Design",
  "Graphic Design",
  "UX/UI Design",
  "Art",
  "Music",
  "Film",
  "Media Studies",
  "Communication",
  "Journalism",
  "Fashion",
  "Information Technology",
  "Cybersecurity",
  "Networking",
  "Cloud Computing",
  "DevOps",
  "Web Development",
  "Mobile Development",
  "Game Development",
  "Robotics",
  "Electronics",
  "Mechanical Trades",
  "Civil Trades",
  "Automotive",
  "Construction",
  "General Knowledge",
  "Reference",
  "Productivity",
  "Self Improvement",
  "Career Development",
  "Test Prep",
  "Certifications",
  "Other",
  "Arithmetic",
  "Pre-Algebra",
  "Algebra",
  "Algebra II",
  "Geometry",
  "Trigonometry",
  "Precalculus",
  "Calculus",
  "Differential Calculus",
  "Integral Calculus",
  "Multivariable Calculus",
  "Linear Algebra",
  "Abstract Algebra",
  "Number Theory",
  "Discrete Mathematics",
  "Combinatorics",
  "Probability",
  "Mathematical Logic",
  "Set Theory",
  "Differential Equations",
  "Partial Differential Equations",
  "Numerical Analysis",
  "Optimization",
  "Real Analysis",
  "Complex Analysis",
  "Topology",
  "Graph Theory",
  "Applied Mathematics",
  "Classical Mechanics",
  "Thermodynamics",
  "Electromagnetism",
  "Optics",
  "Waves",
  "Acoustics",
  "Fluid Mechanics",
  "Quantum Mechanics",
  "Relativity",
  "Nuclear Physics",
  "Particle Physics",
  "Solid State Physics",
  "Astrophysics",
  "Computational Physics",
  "Experimental Physics",
  "General Chemistry",
  "Organic Chemistry",
  "Inorganic Chemistry",
  "Physical Chemistry",
  "Analytical Chemistry",
  "Biochemistry",
  "Environmental Chemistry",
  "Industrial Chemistry",
  "Polymer Chemistry",
  "Medicinal Chemistry",
  "Thermochemistry",
  "Electrochemistry",
  "Cell Biology",
  "Molecular Biology",
  "Genetics",
  "Human Biology",
  "Zoology",
  "Botany",
  "Ecology",
  "Evolution",
  "Marine Biology",
  "Biotechnology",
  "Immunology",
  "Developmental Biology",
  "Programming",
  "Data Structures",
  "Algorithms",
  "Databases",
  "Operating Systems",
  "Computer Networks",
  "Software Engineering",
  "Computer Architecture",
  "Theory of Computation",
  "Compiler Design",
  "Distributed Systems",
  "Parallel Computing",
  "Human Computer Interaction",
  "Information Retrieval",
  "Computer Graphics",
  "Systems Design",
  "HTML",
  "CSS",
  "JavaScript",
  "TypeScript",
  "Frontend Development",
  "Backend Development",
  "Full Stack Development",
  "APIs",
  "REST",
  "GraphQL",
  "Authentication",
  "Authorization",
  "Performance Optimization",
  "Testing",
  "Accessibility",
  "Responsive Design",
  "Android",
  "iOS",
  "React Native",
  "Flutter",
  "Kotlin",
  "Swift",
  "Mobile UI",
  "Mobile Performance",
  "Mobile Security",
  "Deep Learning",
  "Neural Networks",
  "Natural Language Processing",
  "Computer Vision",
  "Reinforcement Learning",
  "Data Analysis",
  "Data Visualization",
  "Data Mining",
  "Feature Engineering",
  "Model Evaluation",
  "MLOps",
  "Big Data",
  "Network Security",
  "Application Security",
  "Cryptography",
  "Ethical Hacking",
  "Penetration Testing",
  "Digital Forensics",
  "Malware Analysis",
  "Identity and Access Management",
  "Security Operations",
  "Secure Coding",
  "Threat Modeling",
  "Mechanical Engineering",
  "Civil Engineering",
  "Electrical Engineering",
  "Chemical Engineering",
  "Biomedical Engineering",
  "Aerospace Engineering",
  "Materials Engineering",
  "Industrial Engineering",
  "Mechatronics",
  "Control Systems",
  "Signal Processing",
  "Pharmacology",
  "Surgery",
  "Internal Medicine",
  "Pediatrics",
  "Cardiology",
  "Neurology",
  "Dermatology",
  "Radiology",
  "Emergency Medicine",
  "Psychiatry",
  "Epidemiology",
  "Clinical Skills",
  "Business Strategy",
  "Organizational Behavior",
  "Sales",
  "Operations Management",
  "Project Management",
  "Product Management",
  "Business Analytics",
  "Customer Service",
  "Corporate Finance",
  "Personal Finance",
  "Investment",
  "Financial Modeling",
  "Banking",
  "Risk Management",
  "Auditing",
  "Taxation",
  "Managerial Accounting",
  "Financial Accounting",
  "Microeconomics",
  "Macroeconomics",
  "Econometrics",
  "International Economics",
  "Behavioral Economics",
  "Constitutional Law",
  "Criminal Law",
  "Civil Law",
  "Contract Law",
  "Tort Law",
  "Property Law",
  "Corporate Law",
  "International Law",
  "Intellectual Property",
  "Labor Law",
  "Tax Law",
  "Family Law",
  "Environmental Law",
  "Legal Writing",
  "Case Law",
  "Cognitive Psychology",
  "Developmental Psychology",
  "Clinical Psychology",
  "Social Psychology",
  "Behavioral Psychology",
  "Neuropsychology",
  "Counseling",
  "Research Methods in Psychology",
  "Social Work",
  "Gender Studies",
  "Ancient History",
  "Medieval History",
  "Modern History",
  "World History",
  "US History",
  "European History",
  "Asian History",
  "African History",
  "Middle Eastern History",
  "Latin American History",
  "Military History",
  "Economic History",
  "English Literature",
  "American Literature",
  "Comparative Literature",
  "Poetry",
  "Pamphlet",
  "Fiction",
  "Drama",
  "Literary Theory",
  "Grammar",
  "Composition",
  "Rhetoric",
  "Creative Writing",
  "Technical Writing",
  "Academic Writing",
  "Translation Studies",
  "Lesson Planning",
  "Classroom Management",
  "Educational Psychology",
  "Curriculum Design",
  "Instructional Design",
  "Assessment",
  "Special Education",
  "Early Childhood Education",
  "Higher Education",
  "Learning Theory",
  "Drawing",
  "Painting",
  "Sculpture",
  "Photography",
  "Film Studies",
  "Animation",
  "Typography",
  "Branding",
  "UX Design",
  "UI Design",
  "Product Design",
  "Illustration",
  "Music Theory",
  "Composition Studies",
  "Media Production",
  "SAT",
  "ACT",
  "GRE",
  "GMAT",
  "LSAT",
  "MCAT",
  "IELTS",
  "TOEFL",
  "CPA",
  "CFA",
  "PMP",
  "AWS Certification",
  "Azure Certification",
  "Google Certification",
  "Cisco Certification",
  "CompTIA",
  "Resume Writing",
  "Cover Letters",
  "Interview Prep",
  "Career Planning",
  "Time Management",
  "Note Taking",
  "Study Skills",
  "Research Skills",
  "Communication Skills",
  "Leadership",
  "Lecture Notes",
  "Study Notes",
  "Class Notes",
  "Revision Notes",
  "Summary",
  "Chapter Summary",
  "Course Outline",
  "Syllabus",
  "Study Guide",
  "Textbook",
  "Workbook",
  "Worksheet",
  "Practice Problems",
  "Problem Set",
  "Assignment",
  "Homework",
  "Lab Manual",
  "Lab Report",
  "Research Paper",
  "Thesis",
  "Dissertation",
  "Abstract",
  "Literature Review",
  "Case Study",
  "Seminar Paper",
  "Tutorial",
  "Reference Sheet",
  "Formula Sheet",
  "Cheat Sheet",
  "Flashcards",
  "Past Paper",
  "Mock Exam",
  "Exam Paper",
  "Answer Key",
  "Mark Scheme",
  "Solution Manual",
  "Resume",
  "CV",
  "Cover Letter",
  "Portfolio",
  "Proposal",
  "Business Plan",
  "Whitepaper",
  "Policy Document",
  "Procedure Document",
  "SOP",
  "Manual",
  "User Guide",
  "Training Guide",
  "Handbook",
  "Report",
  "Annual Report",
  "Financial Report",
  "Market Research Report",
  "Audit Report",
  "Project Plan",
  "Roadmap",
  "Requirements Document",
  "Technical Specification",
  "Product Specification",
  "Design Document",
  "Architecture Document",
  "Meeting Notes",
  "Memo",
  "Invoice",
  "Receipt",
  "Contract",
  "Agreement",
  "Legal Brief",
  "Compliance Document",
  "Presentation",
  "Pitch Deck",
  "Slides",
  "Poster",
  "Infographic",
  "Brochure",
  "Flyer",
  "Newsletter",
  "API Documentation",
  "Developer Guide",
  "Setup Guide",
  "Installation Guide",
  "Configuration Guide",
  "Troubleshooting Guide",
  "Runbook",
  "Diagram Collection",
  "Blueprint",
  "CAD Reference",
  "Network Diagram",
  "System Design Document",
  "Script",
  "Screenplay",
  "Storyboard",
  "Sheet Music",
  "Composition Notes",
  "Art Portfolio",
  "Design Portfolio",
  "Template",
  "Checklist",
  "Planner",
  "Calendar",
  "Tracker",
  "Journal",
  "Logbook",
  "Forms",
  "Reference Document",
  "Miscellaneous",
  "Elementary School",
  "Middle School",
  "High School",
  "College",
  "University",
  "Undergraduate",
  "Graduate",
  "Postgraduate",
  "Doctoral",
  "Professional",
  "Continuing Education",
  "Self Study",
  "Beginner",
  "Introductory",
  "Intermediate",
  "Advanced",
  "Expert",
  "Mixed Level",
  "Students",
  "Teachers",
  "Professors",
  "Researchers",
  "Professionals",
  "Job Seekers",
  "Developers",
  "Designers",
  "Engineers",
  "Medical Students",
  "Law Students",
  "Business Students",
  "Test Takers",
  "General Readers",
  "Hobbyists",
  "Teams",
  "Managers",
  "Founders",
  "Analysts",
  "Educators",
  "PDF",
  "Scanned PDF",
  "Searchable PDF",
  "OCR Processed",
  "Image Based",
  "Text Based",
  "Illustrated",
  "Annotated",
  "Highlighted",
  "Fillable Form",
  "Printable",
  "Mobile Friendly",
  "Low Resolution",
  "High Resolution",
  "Black and White",
  "Color",
  "Single Page",
  "Multi Page",
  "Exam Prep",
  "Homework Help",
  "Quick Reference",
  "Deep Study",
  "Research",
  "Teaching Material",
  "Classroom Use",
  "Personal Learning",
  "Team Training",
  "Onboarding",
  "Certification Prep",
  "Project Work",
  "Client Delivery",
  "Compliance",
  "Documentation",
  "Internal Use",
  "Public Resource",
  "Software",
  "Healthcare",
  "Legal",
  "Manufacturing",
  "Government",
  "Nonprofit",
  "Media",
  "Retail",
  "Logistics",
  "Energy",
  "Telecommunications",
  "Problem Solving",
  "Critical Thinking",
  "Analysis",
  "Writing",
  "Communication",
  "Presentation Skills",
  "Research Methods",
  "Data Interpretation",
  "Coding",
  "Debugging",
  "Design Thinking",
  "Strategic Thinking",
  "Collaboration",
  "Organization",
  "Memorization",
  "Revision",
  "Experimentation",
  "Free",
  "Premium",
  "Verified",
  "Featured",
  "Trending",
  "New",
  "Updated",
  "Popular",
  "Staff Pick",
  "Community Upload",
  "Original",
  "Remixed",
  "Editable",
  "Downloadable",
  "View Only",
  "Restricted Access",
  "Beginner Friendly",
  "Concise",
  "Comprehensive",
  "Visual",
  "Step by Step",
  "Practical",
  "Theoretical",
  "Exam Focused",
  "Industry Relevant",
  "Research Backed",
  "Latest",
  "Recently Updated",
  "Archived",
  "Evergreen",
  "Most Downloaded",
  "Most Viewed",
  "Most Shared",
  "Highly Rated",
  "Reviewed",
  "Approved",
  "Flagged",
  "Needs Review",
  "Group Project",
  "Class Shared",
  "Instructor Provided",
  "Community Contributed",
  "High School Level",
  "College Level",
  "Graduate Level",
  "Professional Level",
  "Beginner Level",
  "Intermediate Level",
  "Advanced Level",
  "Expert Level",
  "All Levels",
  "Hospitality and Tourism Management",
  "Sports Management",
  "Event Management",
  "Public Relations",
  "Advertising",
  "Media Planning",
  "Brand Management",
  "Market Research",
  "Consumer Behavior",
  "Digital Marketing",
  "Content Marketing",
  "Social Media Marketing",
  "Email Marketing",
  "Search Engine Optimization (SEO)",
  "Search Engine Marketing (SEM)",
  "Affiliate Marketing",
  "Influencer Marketing",
  "Marketing Analytics",
  "Hospitality and Tourism Industry Management",
  "Tourism Planning and Sustainability",
  "Destination Development",
  "Hotel and Lodging Management",
  "Food and Beverage Management",
  "Travel and Tourism Operations Management",
  "Tourism Marketing and Digital Promotion",
  "Entrepreneurship in Hospitality and Tourism",
  "Bachelor in Physics",
  "Master in Physics",
  "PhD in Physics",
  "Year 1",
  "Year 2",
  "Year 3",
  "Year 4",
  "Year 5",
  "Year 6",
  "Grade 1",
  "Grade 2",
  "Grade 3",
  "Grade 4",
  "Grade 5",
  "Grade 6",
  "Grade 7",
  "Grade 8",
  "Grade 9",
  "Grade 10",
  "Grade 11",
  "Grade 12",
  "Freshman",
  "Sophomore",
  "Junior",
  "Senior",
  "Form 1",
  "Form 2",
  "Form 3",
  "Form 4",
  "Form 5",
  "University of Zambia",
  "Copperbelt University",
  "Mulungushi University",
  "Levy Mwanawasa Medical University",
  "Cavendish University Zambia",
  "University of Lusaka",
  "Zambian Open University",
  "Information and Communications University",
  "ZCAS University",
  "Mukuba University",
  "Kwame Nkrumah University",
  "Chalimbana University",
  "Kapasa Makasa University",
  "Northrise University",
  "Lusaka Apex Medical University",
  "DMI St. Eugene University",
  "Texila American University Zambia",
  "University of Africa",
  "Rockview University",
  "Victoria Falls University of Technology",
  "Zambia Catholic University",
  "Eden University",
  "Unicaf University Zambia",
  "Gideon Robert University",
  "Copperstone University",
  "Zambia Open University",
  "National Institute of Public Administration",
  "Evelyn Hone College",
  "Natural Resources Development College",
] as const;

const CATEGORY_LOOKUP = new Map(
  POST_CATEGORIES.map((category) => [category.toLowerCase(), category]),
);

export function normalizeAllowedCategory(value: string): string | null {
  const normalized = value.trim().toLowerCase();
  if (!normalized) return null;

  return CATEGORY_LOOKUP.get(normalized) ?? null;
}
